// Friendly aliases over Orval-generated Zod schemas. Orval names schemas
// after operationId+role (e.g. UpdateMatchResponse) rather than entity name,
// so we re-export them under intuitive names for use in route handlers.
export {
  GetCurrentUserResponse as AuthUser,
  ListTournamentsResponseItem as Tournament,
  GetTournamentResponse as TournamentDetail,
  JoinTournamentResponse as Participant,
  CreateMatchBody as MatchInput,
  UpdateMatchBody as MatchUpdate,
  UpdateMatchResponse as Match,
  ListMatchesResponseItem as MatchWithPrediction,
  EnterMatchResultBody as MatchResultInput,
  ImportMatchesCsvBody as CsvImportInput,
  ImportMatchesCsvResponse as ImportSummary,
  SubmitPredictionBody as PredictionInput,
  SubmitPredictionResponse as Prediction,
  GetLeaderboardResponseItem as LeaderboardEntry,
  UpdateMyProfileBody as ProfileUpdate,
  GetMyStatsResponse as UserStats,
  ListTeamsResponseItem as Team,
  CreateTeamBody as TeamInput,
  GetAdminOverviewResponse as AdminOverview,
  ListAdminUsersResponseItem as AdminUserRow,
  GetAdminPredictionsResponseItem as MatchPredictionSummary,
  SyncFixturesBody as SyncRequest,
  SyncFixturesResponse,
  SyncScoresResponse,
  GetSyncStatusResponse as SyncStatus,
  GetTeamFormResponse as TeamForm,
  GetMatchLineupsResponse as MatchLineups,
  // Verification + payment + identity
  VerifyOtpBody as VerifyOtpInput,
  GetMyAccountStatusResponse as AccountStatus,
  UpdateMyAvatarBody as SubmitAvatarInput,
  SubmitPaymentBody as SubmitPaymentInput,
  SubmitIdentityBody as SubmitIdentityInput,
  GetPaymentSettingsResponse as PaymentSettings,
  UpdatePaymentSettingsBody as PaymentSettingsInput,
  ListPendingPaymentsResponseItem as PendingPayment,
  ListPendingIdentitiesResponseItem as PendingIdentity,
  DecideUserPaymentBody as AdminDecisionInput,
  RequestUploadUrlBody as UploadUrlRequest,
  RequestUploadUrlResponse as UploadUrlResponse,
} from "@workspace/api-zod";
